import BeyondSperner.Simplicial.FacetChain
import BeyondSperner.Freudenthal.CellClassification

/-!
# The Freudenthal complex attached to the integer simplex

This file constructs the target complex needed for Theorem 4.8 independently
of Scarf cells.  Its facets are actual permutation step simplices whose
vertices all lie in `Point N n`; Lemma 4.6 identifies their cumulative
coordinate images with the usual Freudenthal vertex sets.

Only the forward inclusion from the Scarf complex into this complex is proved
in this module.  The reverse inclusion, equality of top chains, and Corollary
4.10 are proved later in `FreudenthalBoundary`; they are deliberately not
built into the definition.
-/

namespace BeyondSperner

open Classical

namespace IntegerSimplex

variable {N n : ℕ}

/-- A set of points is a genuine top-dimensional permutation step simplex.
The equality is tested after the injective coordinate embedding, so it also
asserts that every vertex of the step simplex is represented in `Point N n`. -/
def IsFreudenthalTopSimplex (rho : Finset (Point N n)) : Prop :=
  ∃ a : Point N n, ∃ omega : Equiv.Perm (Fin n),
    rho.image pointCoords =
      stepSimplex (pointCoords a) (permutationList omega)

/-- Faces of genuine Freudenthal top simplices, including the empty face. -/
def IsFreudenthalSimplex (tau : Finset (Point N n)) : Prop :=
  tau = ∅ ∨ ∃ rho : Finset (Point N n),
    IsFreudenthalTopSimplex rho ∧ tau ⊆ rho

theorem IsFreudenthalSimplex.of_subset {sigma tau : Finset (Point N n)}
    (hsigma : IsFreudenthalSimplex sigma) (htau : tau ⊆ sigma) :
    IsFreudenthalSimplex tau := by
  rcases hsigma with rfl | ⟨rho, hrho, hsigma⟩
  · left
    exact Finset.Subset.antisymm htau (Finset.empty_subset tau)
  · exact Or.inr ⟨rho, hrho, htau.trans hsigma⟩

/-- The finite abstract complex generated by the permutation step simplices
contained in the integer simplex. -/
noncomputable def freudenthalComplex (N n : ℕ) :
    FiniteSimplicialComplex (Point N n) where
  simplices := Finset.univ.filter IsFreudenthalSimplex
  empty_mem := by
    apply Finset.mem_filter.mpr
    exact ⟨Finset.mem_univ _, Or.inl rfl⟩
  downward_closed := by
    intro sigma tau hsigma htau
    apply Finset.mem_filter.mpr
    exact ⟨Finset.mem_univ _, IsFreudenthalSimplex.of_subset
      (Finset.mem_filter.mp hsigma).2 htau⟩

theorem mem_freudenthalComplex_iff (tau : Finset (Point N n)) :
    tau ∈ freudenthalComplex N n ↔ IsFreudenthalSimplex tau := by
  change tau ∈ Finset.univ.filter IsFreudenthalSimplex ↔ _
  simp

/-- A Freudenthal top simplex has the expected `n+1` vertices. -/
theorem IsFreudenthalTopSimplex.card {rho : Finset (Point N n)}
    (hrho : IsFreudenthalTopSimplex rho) : rho.card = n + 1 := by
  obtain ⟨a, omega, heq⟩ := hrho
  rw [← Finset.card_image_of_injective rho pointCoords_injective]
  rw [heq, card_stepSimplex_permutation]

theorem IsFreudenthalTopSimplex.mem_complex {rho : Finset (Point N n)}
    (hrho : IsFreudenthalTopSimplex rho) :
    rho ∈ freudenthalComplex N n := by
  apply (mem_freudenthalComplex_iff rho).2
  exact Or.inr ⟨rho, hrho, Finset.Subset.rfl⟩

/-- The finite set of facets of the Freudenthal complex.  Keeping this as an
explicit finset makes the chain arguments in Theorem 4.8 independent of any
implicit maximality convention. -/
noncomputable def freudenthalFacets (N n : ℕ) :
    Finset (Finset (Point N n)) :=
  Finset.univ.filter IsFreudenthalTopSimplex

theorem mem_freudenthalFacets_iff (rho : Finset (Point N n)) :
    rho ∈ freudenthalFacets N n ↔ IsFreudenthalTopSimplex rho := by
  simp [freudenthalFacets]

/-- The existentially presented step simplices are exactly the simplices of
cardinality `n+1` in the generated complex.  Thus no larger or spurious face
has silently entered the facet set. -/
theorem freudenthalFacets_eq_topSimplices :
    freudenthalFacets N n =
      (freudenthalComplex N n).topSimplices (n + 1) := by
  ext tau
  constructor
  · intro htau
    have htop := (mem_freudenthalFacets_iff tau).1 htau
    exact Finset.mem_filter.mpr ⟨htop.mem_complex, htop.card⟩
  · intro htau
    have hdata := Finset.mem_filter.mp htau
    have hsimp := (mem_freudenthalComplex_iff tau).1 hdata.1
    apply (mem_freudenthalFacets_iff tau).2
    rcases hsimp with hzero | ⟨rho, hrho, hsub⟩
    · subst tau
      simp at hdata
    · have heq : tau = rho := Finset.eq_of_subset_of_card_le hsub (by
        rw [hrho.card, hdata.2])
      simpa [heq] using hrho

/-- The facet set is pure of the expected dimension, one of the four concrete
hypotheses needed by `FacetChain.eq_sum_of_boundary_eq`. -/
theorem freudenthalFacets_isPure :
    FacetChain.IsPure (freudenthalFacets N n) n := by
  intro rho hrho
  exact ((mem_freudenthalFacets_iff rho).1 hrho).card

/-- The positive-scale hypothesis needed later is real, not cosmetic.  If
`N = 0` in positive dimension, the point type is a singleton and there are no
`n`-dimensional Freudenthal facets. -/
theorem freudenthalFacets_zero_eq_empty (hn : 0 < n) :
    freudenthalFacets 0 n = ∅ := by
  apply Finset.eq_empty_iff_forall_notMem.mpr
  intro rho hrho
  have hcard := ((mem_freudenthalFacets_iff rho).1 hrho).card
  have hle : rho.card ≤ 1 := by
    apply Finset.card_le_one_iff.mpr
    intro a ha b hb
    apply Subtype.ext
    funext i
    apply Fin.ext
    omega
  omega

theorem freudenthalFacets_zero_not_hasNonemptyBoundary (hn : 0 < n) :
    ¬ FacetChain.HasNonemptyBoundary (freudenthalFacets 0 n) n := by
  rw [freudenthalFacets_zero_eq_empty hn]
  rintro ⟨rho, hrho, hcofaces⟩
  simp at hcofaces

/-- The actual top chain of the Freudenthal complex, with coefficient one on
each genuine step simplex. -/
noncomputable def freudenthalTopChain (N n : ℕ) :
    SimplexFamily.Chain (Point N n) :=
  FacetChain.sum (freudenthalFacets N n)

@[simp]
theorem freudenthalTopChain_apply (rho : Finset (Point N n)) :
    freudenthalTopChain N n rho =
      if IsFreudenthalTopSimplex rho then 1 else 0 := by
  simp [freudenthalTopChain, mem_freudenthalFacets_iff]

/-- This is genuinely an `n`-dimensional abstract complex: every simplex has
at most `n+1` vertices. -/
theorem freudenthalComplex_card_le {tau : Finset (Point N n)}
    (htau : tau ∈ freudenthalComplex N n) : tau.card ≤ n + 1 := by
  have hsimp := (mem_freudenthalComplex_iff tau).1 htau
  rcases hsimp with rfl | ⟨rho, hrho, hsub⟩
  · simp
  · exact (Finset.card_le_card hsub).trans_eq hrho.card

/-- The cumulative-coordinate image is exactly the standard Freudenthal
vertex set, not merely a set with the same cardinality. -/
theorem IsFreudenthalTopSimplex.image_pointPrefix
    {rho : Finset (Point N n)} (hrho : IsFreudenthalTopSimplex rho) :
    ∃ a : Point N n, ∃ omega : Equiv.Perm (Fin n),
      rho.image pointPrefix =
        freudenthalSimplex (pointPrefix a) (permutationList omega) := by
  obtain ⟨a, omega, heq⟩ := hrho
  refine ⟨a, omega, ?_⟩
  rw [pointPrefix, ← image_prefixMap_stepSimplex]
  rw [← heq]
  ext y
  simp [pointPrefix]

/-- The paper's target-side presentation: a top simplex is a standard
Freudenthal vertex set after applying cumulative coordinates.  Since `rho`
already consists of points of `Point N n`, containment in `Γ` is built into
the type rather than added as a separate unchecked predicate. -/
def IsCumulativeFreudenthalTopSimplex (rho : Finset (Point N n)) : Prop :=
  ∃ u : Fin n → ℤ, ∃ omega : Equiv.Perm (Fin n),
    rho.image pointPrefix =
      freudenthalSimplex u (permutationList omega)

private theorem image_pointCoords_eq_stepSimplex_of_prefix_eq
    {rho : Finset (Point N n)} {a : Point N n} {l : List (Fin n)}
    (hprefix : rho.image pointPrefix =
      freudenthalSimplex (pointPrefix a) l) :
    rho.image pointCoords = stepSimplex (pointCoords a) l := by
  have himage :
      (rho.image pointCoords).image prefixMap =
        (stepSimplex (pointCoords a) l).image prefixMap := by
    calc
      (rho.image pointCoords).image prefixMap =
          rho.image pointPrefix := by
        ext y
        simp [pointPrefix]
      _ = freudenthalSimplex (pointPrefix a) l := hprefix
      _ = (stepSimplex (pointCoords a) l).image prefixMap :=
        (image_prefixMap_stepSimplex (pointCoords a) l).symm
  ext x
  constructor
  · intro hx
    have hpx : prefixMap x ∈
        (stepSimplex (pointCoords a) l).image prefixMap := by
      rw [← himage]
      exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
    obtain ⟨z, hz, hzx⟩ := Finset.mem_image.mp hpx
    obtain ⟨b, _, rfl⟩ := Finset.mem_image.mp hx
    have hzsum : ∑ i, z i = (N : ℤ) :=
      (sum_eq_of_mem_stepSimplex (pointCoords a) l hz).trans
        (pointCoords_isPoint a).2
    have heq : z = pointCoords b := prefixMap_injective_on_sum
      hzsum (pointCoords_isPoint b).2 hzx
    simpa [heq] using hz
  · intro hx
    have hpx : prefixMap x ∈ (rho.image pointCoords).image prefixMap := by
      rw [himage]
      exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
    obtain ⟨z, hz, hzx⟩ := Finset.mem_image.mp hpx
    obtain ⟨b, hbrho, rfl⟩ := Finset.mem_image.mp hz
    have hxsum : ∑ i, x i = (N : ℤ) :=
      (sum_eq_of_mem_stepSimplex (pointCoords a) l hx).trans
        (pointCoords_isPoint a).2
    have heq : pointCoords b = x := prefixMap_injective_on_sum
      (pointCoords_isPoint b).2 hxsum hzx
    exact Finset.mem_image.mpr ⟨b, hbrho, heq⟩

/-- Full finite-set form of Lemma 4.6: the original-coordinate transfer
presentation and the cumulative-coordinate Freudenthal presentation are
equivalent.  The reverse implication is derived from equal prefix images and
the fixed-sum injectivity theorem, not assumed as part of the definition. -/
theorem isFreudenthalTopSimplex_iff_cumulative
    (rho : Finset (Point N n)) :
    IsFreudenthalTopSimplex rho ↔
    IsCumulativeFreudenthalTopSimplex rho := by
  constructor
  · intro hrho
    obtain ⟨a, omega, heq⟩ := hrho.image_pointPrefix
    exact ⟨pointPrefix a, omega, heq⟩
  · rintro ⟨u, omega, heq⟩
    have huFreud : u ∈ freudenthalSimplex u (permutationList omega) := by
      cases permutationList omega <;>
        simp [freudenthalSimplex, freudenthalSequence]
    have huRho : u ∈ rho.image pointPrefix := by
      rw [heq]
      exact huFreud
    obtain ⟨a, _, hau⟩ := Finset.mem_image.mp huRho
    refine ⟨a, omega, image_pointCoords_eq_stepSimplex_of_prefix_eq ?_⟩
    simpa [hau] using heq

/-- Theorem 4.5 supplies the forward facet map required in Theorem 4.8. -/
theorem isFreudenthalTopSimplex_of_isCell
    {sigma : Finset (Point N n)}
    (hcell : (pointOrders N n).IsCell sigma Finset.univ) :
    IsFreudenthalTopSimplex sigma := by
  obtain ⟨a, _, omega, heq⟩ := theorem4_5 hcell
  exact ⟨a, omega, heq⟩

/-- Proven half of the complex isomorphism in Theorem 4.8: every simplex of
`T(I)` is a face of a genuine Freudenthal top simplex. -/
theorem associatedComplex_subset_freudenthalComplex :
    ∀ {tau : Finset (Point N n)},
      tau ∈ (pointOrders N n).associatedComplex Finset.univ →
        tau ∈ freudenthalComplex N n := by
  intro tau htau
  have hassoc : (pointOrders N n).IsAssociatedSimplex Finset.univ tau :=
    (Finset.mem_filter.mp htau).2
  have huniv : (Finset.univ : Finset (Fin (n + 1))) ≠ ∅ := by
    intro h
    have hzero : (0 : Fin (n + 1)) ∈
        (Finset.univ : Finset (Fin (n + 1))) := Finset.mem_univ _
    rw [h] at hzero
    simp at hzero
  rw [IndexedLinearOrders.IsAssociatedSimplex, if_neg huniv] at hassoc
  apply (mem_freudenthalComplex_iff tau).2
  rcases hassoc with rfl | ⟨sigma, hcell, hsub⟩
  · exact Or.inl rfl
  · exact Or.inr ⟨sigma, isFreudenthalTopSimplex_of_isCell hcell, hsub⟩

/-- The top chain on the Scarf associated complex occurring on the left of
equation (20). -/
noncomputable def associatedTopChain (N n : ℕ) :
    SimplexFamily.Chain (Point N n) :=
  (pointOrders N n).associatedFamily.topChain Finset.univ

/-- The forward simplex map already proved above implies the stronger
chain-level fact needed by the uniqueness argument: the Scarf top chain has
no coefficient outside the genuine Freudenthal facet set. -/
theorem associatedTopChain_supportedOn :
    FacetChain.SupportedOn (associatedTopChain N n)
      (freudenthalFacets N n) := by
  intro sigma hsigma
  rw [associatedTopChain, SimplexFamily.topChain_apply, if_neg]
  intro htop
  apply hsigma
  rw [freudenthalFacets_eq_topSimplices]
  apply Finset.mem_filter.mpr
  refine ⟨associatedComplex_subset_freudenthalComplex htop.1, ?_⟩
  simpa using htop.2

/-- The exact final implication in the proof of Theorem 4.8.  Unlike a
statement-only triangulation interface, this reusable implication exposes
the three combinatorial properties of the concrete facet set and the
inductively established boundary equality as explicit hypotheses.  They are
discharged later in `FreudenthalConnectivity` and `FreudenthalBoundary`. -/
theorem associatedTopChain_eq_freudenthalTopChain_of_boundary_eq
    (hnb : FacetChain.Nonbranching (freudenthalFacets N n) n)
    (hconn : FacetChain.StronglyFacetConnected
      (freudenthalFacets N n) n)
    (hboundary : FacetChain.HasNonemptyBoundary
      (freudenthalFacets N n) n)
    (hboundaryEq :
      SimplexFamily.boundary (associatedTopChain N n) =
        SimplexFamily.boundary (freudenthalTopChain N n)) :
    associatedTopChain N n = freudenthalTopChain N n := by
  exact FacetChain.eq_sum_of_boundary_eq freudenthalFacets_isPure
    hnb hconn hboundary associatedTopChain_supportedOn hboundaryEq

/-- Equality of the two top chains really implies equality of the two
complexes.  Both directions are proved from the concrete definitions: the
forward inclusion is Theorem 4.5, while a coefficient-one Freudenthal facet
is forced by the chain equality to be a top simplex of the associated
complex, whose downward closure then contains all its faces. -/
theorem associatedComplex_eq_freudenthalComplex_of_topChain_eq
    (hchain : associatedTopChain N n = freudenthalTopChain N n) :
    (pointOrders N n).associatedComplex Finset.univ =
      freudenthalComplex N n := by
  apply FiniteSimplicialComplex.ext
  ext tau
  constructor
  · intro htau
    exact associatedComplex_subset_freudenthalComplex htau
  · intro htau
    have hsimp := (mem_freudenthalComplex_iff tau).1 htau
    rcases hsimp with rfl | ⟨rho, hrho, hsub⟩
    · exact ((pointOrders N n).associatedComplex Finset.univ).empty_mem
    · have hcoeff := congrArg (fun c ↦ c rho) hchain
      rw [associatedTopChain, SimplexFamily.topChain_apply,
        freudenthalTopChain_apply, if_pos hrho] at hcoeff
      have hrhoAssociatedTop :
          rho ∈ ((pointOrders N n).associatedComplex Finset.univ).simplices ∧
            rho.card = (Finset.univ : Finset (Fin (n + 1))).card := by
        by_contra hnot
        have hnot' : ¬(rho ∈
            ((pointOrders N n).associatedFamily.complex
              Finset.univ).simplices ∧
            rho.card = (Finset.univ : Finset (Fin (n + 1))).card) := by
          simpa [IndexedLinearOrders.associatedFamily] using hnot
        rw [if_neg hnot'] at hcoeff
        exact zero_ne_one hcoeff
      exact ((pointOrders N n).associatedComplex Finset.univ).downward_closed
        hrhoAssociatedTop.1 hsub

/-- A reusable implication for the complex statement of Theorem 4.8.  Its
hypotheses deliberately expose, rather than assume globally, the
positive-dimensional Freudenthal geometry and the inductive boundary
identity; later modules prove all four hypotheses. -/
theorem associatedComplex_eq_freudenthalComplex_of_boundary_eq
    (hnb : FacetChain.Nonbranching (freudenthalFacets N n) n)
    (hconn : FacetChain.StronglyFacetConnected
      (freudenthalFacets N n) n)
    (hboundary : FacetChain.HasNonemptyBoundary
      (freudenthalFacets N n) n)
    (hboundaryEq :
      SimplexFamily.boundary (associatedTopChain N n) =
        SimplexFamily.boundary (freudenthalTopChain N n)) :
    (pointOrders N n).associatedComplex Finset.univ =
      freudenthalComplex N n := by
  apply associatedComplex_eq_freudenthalComplex_of_topChain_eq
  exact associatedTopChain_eq_freudenthalTopChain_of_boundary_eq
    hnb hconn hboundary hboundaryEq

end IntegerSimplex

end BeyondSperner
