import BeyondSperner.OrientedMatroid.Core
import BeyondSperner.OrientedMatroid.WeakStrongElimination
import BeyondSperner.OrientedMatroid.Basic
import BeyondSperner.OrientedMatroid.CocircuitElimination
import BeyondSperner.OrientedMatroid.Dual
import BeyondSperner.OrientedMatroid.Elimination
import BeyondSperner.OrientedMatroid.Farkas
import BeyondSperner.OrientedMatroid.LexicographicCircuit
import BeyondSperner.OrientedMatroid.LexicographicExtensionConstruction
import BeyondSperner.OrientedMatroid.LexicographicSecondary
import BeyondSperner.OrientedMatroid.LexicographicLocalization
import BeyondSperner.OrientedMatroid.OrthogonalPairElimination
import BeyondSperner.OrientedMatroid.Todd

/-! Umbrella module for the oriented-matroid layer of the Ivanov formalization. -/
