import BeyondSperner.Euclidean.Intersection.Basic
import Mathlib.Analysis.Normed.Affine.AddTorsorBases
import Mathlib.Analysis.Normed.Module.Convex

/-!
# The escape-to-general-position lemma of Section 10

This file proves Lemma 10.2 of Ivanov's *Beyond Sperner's Lemma*.  The
positive-dimensional hypothesis is explicit: in dimension zero there are no
one-simplices, so the premise about their boundaries would be vacuous while
the conclusion can fail.
-/

namespace BeyondSperner
namespace EuclideanIntersection

open Classical Set
open SimplexFamily

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  [FiniteDimensional ℝ E] [DecidableEq E]

omit [FiniteDimensional ℝ E] [DecidableEq E] in
/-- A finite set with at most `finrank E` points cannot affinely span `E`.
No independence hypothesis on the finite set is needed. -/
theorem affineSpan_ne_top_of_card_le_finrank
    (t : Finset E) (hcard : t.card ≤ Module.finrank ℝ E) :
    affineSpan ℝ (t : Set E) ≠ ⊤ := by
  intro htop
  have htNonempty : (t : Set E).Nonempty :=
    AffineSubspace.nonempty_of_affineSpan_eq_top ℝ E E htop
  let : Nonempty ↥(t : Set E) := htNonempty.to_subtype
  have hdim := finrank_vectorSpan_range_add_one_le ℝ
    ((↑) : ↥(t : Set E) → E)
  have hspan :
      vectorSpan ℝ (Set.range ((↑) : ↥(t : Set E) → E)) = ⊤ := by
    rw [Subtype.range_coe_subtype]
    exact AffineSubspace.vectorSpan_eq_top_of_affineSpan_eq_top ℝ E E htop
  rw [hspan, finrank_top] at hdim
  have hcard' : Module.finrank ℝ E + 1 ≤ t.card := by
    simpa using hdim
  omega

omit [FiniteDimensional ℝ E] [DecidableEq E] in
/-- The affine span of at most `finrank E` points has empty ambient
interior. -/
theorem interior_affineSpan_eq_empty_of_card_le_finrank
    (t : Finset E) (hcard : t.card ≤ Module.finrank ℝ E) :
    interior (affineSpan ℝ (t : Set E) : Set E) = ∅ := by
  by_contra hne
  have hnonempty :
      (interior (affineSpan ℝ (t : Set E) : Set E)).Nonempty :=
    Set.nonempty_iff_ne_empty.mpr hne
  have hinteriorSpan := isOpen_interior.affineSpan_eq_top hnonempty
  have hspanTop : affineSpan ℝ (t : Set E) = ⊤ := by
    apply top_unique
    rw [← hinteriorSpan]
    have hmono :
        affineSpan ℝ (interior (affineSpan ℝ (t : Set E) : Set E)) ≤
          affineSpan ℝ (affineSpan ℝ (t : Set E) : Set E) :=
      affineSpan_mono ℝ interior_subset
    simpa only [AffineSubspace.affineSpan_coe] using hmono
  exact affineSpan_ne_top_of_card_le_finrank t hcard hspanTop

omit [NormedSpace ℝ E] [FiniteDimensional ℝ E] [DecidableEq E] in
/-- A finite union of closed sets with empty interior has empty interior. -/
theorem interior_biUnion_finset_eq_empty
    {ι : Type*} (S : Finset ι) (f : ι → Set E)
    (hclosed : ∀ i ∈ S, IsClosed (f i))
    (hempty : ∀ i ∈ S, interior (f i) = ∅) :
    interior (⋃ i ∈ S, f i) = ∅ := by
  induction S using Finset.induction_on with
  | empty => simp
  | @insert a S ha ih =>
      have hunion : (⋃ i ∈ insert a S, f i) = f a ∪ ⋃ i ∈ S, f i := by
        ext x
        simp
      rw [hunion]
      rw [interior_union_isClosed_of_interior_empty
        (hclosed a (Finset.mem_insert_self a S))]
      · exact hempty a (Finset.mem_insert_self a S)
      · apply ih
        · intro i hi
          exact hclosed i (Finset.mem_insert_of_mem hi)
        · intro i hi
          exact hempty i (Finset.mem_insert_of_mem hi)

omit [FiniteDimensional ℝ E] [DecidableEq E] in
/-- Finite collections of affine spans generated by at most `finrank E`
points form a nowhere-dense obstacle locus. -/
theorem interior_iUnion_affineSpan_eq_empty_of_card_le_finrank
    (S : Finset (Finset E))
    (hcard : ∀ t ∈ S, t.card ≤ Module.finrank ℝ E) :
    interior (⋃ t ∈ S, (affineSpan ℝ (t : Set E) : Set E)) = ∅ := by
  apply interior_biUnion_finset_eq_empty S
  · intro t ht
    let : FiniteDimensional ℝ (affineSpan ℝ (t : Set E)).direction :=
      finiteDimensional_direction_affineSpan_of_finite ℝ t.finite_toSet
    exact AffineSubspace.closed_of_finiteDimensional _
  · intro t ht
    exact interior_affineSpan_eq_empty_of_card_le_finrank t (hcard t ht)

/-- Finite sets controlling all possible codimension-two intersections of a
segment from `z` with a simplex of `c`.  The singleton `{z}` is included so
that escaping the obstacle locus also guarantees a distinct second endpoint. -/
noncomputable def segmentObstacleSets (c : Chain E) (z : E) :
    Finset (Finset E) :=
  insert {z} <|
    c.support.biUnion fun sigma ↦
      sigma.biUnion fun v ↦
        (sigma.erase v).image fun w ↦ insert z ((sigma.erase v).erase w)

/-- Union of the affine obstacles used to choose the escaping endpoint. -/
noncomputable def segmentObstacleLocus (c : Chain E) (z : E) : Set E :=
  ⋃ t ∈ segmentObstacleSets c z,
    (affineSpan ℝ (t : Set E) : Set E)

/-- The geometric support of a Euclidean chain. -/
noncomputable def chainRealization (c : Chain E) : Set E :=
  ⋃ sigma ∈ c.support, realization sigma

omit [FiniteDimensional ℝ E] in
/-- Every obstacle set has at most the ambient dimension many points. -/
theorem segmentObstacleSets_card_le
    (n : ℕ) (c : Chain E) (z : E)
    (hdim : Module.finrank ℝ E = n) (hn : 0 < n)
    (hc : IsMChain n c) :
    ∀ t ∈ segmentObstacleSets c z, t.card ≤ Module.finrank ℝ E := by
  intro t ht
  rw [segmentObstacleSets] at ht
  simp only [Finset.mem_insert, Finset.mem_biUnion, Finset.mem_image] at ht
  rcases ht with rfl | ⟨sigma, hsigma, v, hv, w, hw, rfl⟩
  · simpa [hdim] using (Nat.succ_le_iff.mpr hn)
  · have hsigmaCard : sigma.card = n + 1 := hc sigma hsigma
    have heraseV : (sigma.erase v).card = n := by
      rw [Finset.card_erase_of_mem hv, hsigmaCard]
      omega
    have heraseW : ((sigma.erase v).erase w).card + 1 = n := by
      rw [Finset.card_erase_of_mem hw, heraseV]
      omega
    calc
      (insert z ((sigma.erase v).erase w)).card ≤
          ((sigma.erase v).erase w).card + 1 := Finset.card_insert_le _ _
      _ = n := heraseW
      _ = Module.finrank ℝ E := hdim.symm

omit [FiniteDimensional ℝ E] in
/-- The full obstacle locus has empty interior. -/
theorem interior_segmentObstacleLocus_eq_empty
    (n : ℕ) (c : Chain E) (z : E)
    (hdim : Module.finrank ℝ E = n) (hn : 0 < n)
    (hc : IsMChain n c) :
    interior (segmentObstacleLocus c z) = ∅ := by
  rw [segmentObstacleLocus]
  apply interior_iUnion_affineSpan_eq_empty_of_card_le_finrank
  exact segmentObstacleSets_card_le n c z hdim hn hc

omit [FiniteDimensional ℝ E] in
/-- The geometric support of a finite chain is closed. -/
theorem isClosed_chainRealization (c : Chain E) :
    IsClosed (chainRealization c) := by
  rw [chainRealization]
  apply isClosed_biUnion_finset
  intro sigma hsigma
  exact sigma.finite_toSet.isClosed_convexHull ℝ

omit [FiniteDimensional ℝ E] in
/-- The geometric support of a finite chain is bounded. -/
theorem isBounded_chainRealization (c : Chain E) :
    Bornology.IsBounded (chainRealization c) := by
  rw [chainRealization]
  rw [Bornology.isBounded_biUnion_finset]
  intro sigma hsigma
  rw [realization]
  rw [isBounded_convexHull]
  exact sigma.finite_toSet.isBounded

omit [FiniteDimensional ℝ E] in
/-- There is a point outside both the bounded support of the chain and all
affine obstacles which could force a codimension-two segment intersection. -/
theorem exists_endpoint_outside_chain_and_obstacles
    (n : ℕ) (c : Chain E) (z : E)
    (hdim : Module.finrank ℝ E = n) (hn : 0 < n)
    (hc : IsMChain n c) :
    ∃ u : E, u ∉ chainRealization c ∧ u ∉ segmentObstacleLocus c z := by
  have hfinrankPos : 0 < Module.finrank ℝ E := by
    simpa [hdim] using hn
  let : Nontrivial E := Module.nontrivial_of_finrank_pos hfinrankPos
  have hsupportNeUniv : chainRealization c ≠ Set.univ := by
    intro htop
    apply NormedSpace.unbounded_univ ℝ E
    simpa [htop] using isBounded_chainRealization c
  have hsupportComplNonempty : (chainRealization c)ᶜ.Nonempty :=
    Set.nonempty_compl.mpr hsupportNeUniv
  have hobstacleDense : Dense (segmentObstacleLocus c z)ᶜ :=
    interior_eq_empty_iff_dense_compl.mp
      (interior_segmentObstacleLocus_eq_empty n c z hdim hn hc)
  obtain ⟨u, huObstacle, huSupport⟩ :=
    hobstacleDense.exists_mem_open
      (isClosed_chainRealization c).isOpen_compl hsupportComplNonempty
  exact ⟨u, huSupport, huObstacle⟩

omit [FiniteDimensional ℝ E] in
/-- If the second endpoint avoids the affine span generated by the first
endpoint and a face, then the segment cannot meet that face, provided the
first endpoint itself is outside the realized face. -/
theorem disjoint_segment_realization_of_not_mem_affineSpan_insert
    (tau : Finset E) (z u : E)
    (hz : z ∉ realization tau)
    (hu : u ∉ affineSpan ℝ (insert z tau : Set E)) :
    Disjoint (realization ({z, u} : Finset E)) (realization tau) := by
  apply Set.disjoint_left.mpr
  intro p hpSegment hpFace
  rw [realization_pair, segment_eq_image_lineMap] at hpSegment
  obtain ⟨r, hr, rfl⟩ := hpSegment
  let A := affineSpan ℝ (insert z tau : Set E)
  have hzA : z ∈ A := by
    apply mem_affineSpan ℝ
    simp
  have hpA : AffineMap.lineMap z u r ∈ A := by
    have htauSubset : (tau : Set E) ⊆ insert z (tau : Set E) :=
      Set.subset_insert z _
    exact (affineSpan_mono ℝ htauSubset)
      (convexHull_subset_affineSpan (tau : Set E) hpFace)
  have hrNeZero : r ≠ 0 := by
    intro hrZero
    apply hz
    simpa [hrZero] using hpFace
  have hscaled : r • (u - z) ∈ A.direction := by
    have hscaled' := AffineSubspace.vsub_mem_direction hpA hzA
    rw [AffineMap.lineMap_vsub_left] at hscaled'
    simpa only [vsub_eq_sub] using hscaled'
  have hdirection : u - z ∈ A.direction := by
    have hinv := A.direction.smul_mem r⁻¹ hscaled
    simpa [smul_smul, hrNeZero] using hinv
  apply hu
  have huA := AffineSubspace.vadd_mem_of_mem_direction hdirection hzA
  simpa using huA

/-- A point is in general position with respect to every simplex occurring
in a chain. -/
def PointInGeneralPositionWithChain (c : Chain E) (z : E) : Prop :=
  ∀ sigma ∈ c.support, PointInGeneralPosition sigma z

/-- A literal one-simplex is in general position with respect to every
simplex occurring in a chain. -/
def OneSimplexInGeneralPositionWithChain
    (c : Chain E) (omega : Finset E) : Prop :=
  IsMSimplex 1 omega ∧
    ∀ sigma ∈ c.support, OneSimplexInGeneralPosition sigma omega

omit [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E] in
/-- A basis chain is homogeneous precisely when its unique simplex has the
corresponding dimension.  This removes the first compatibility gap between
the direct simplex predicates and the chain-level interface. -/
@[simp]
theorem isMChain_singletonChain (m : ℕ) (sigma : Finset E) :
    IsMChain m (singletonChain sigma) ↔ IsMSimplex m sigma := by
  simp [IsMChain, IsChainOfCardinality, IsMSimplex, singletonChain]

omit [FiniteDimensional ℝ E] in
/-- For a singleton zero-chain, the chain-level general-position predicate
is exactly the direct pointwise predicate (together with homogeneity of the
left chain). -/
theorem pointChainsInGeneralPosition_singleton_iff
    (n : ℕ) (c : Chain E) (z : E) :
    PointChainsInGeneralPosition n c (singletonChain {z}) ↔
      IsMChain n c ∧ PointInGeneralPositionWithChain c z := by
  constructor
  · rintro ⟨hc, -, hgp⟩
    refine ⟨hc, ?_⟩
    intro sigma hsigma
    exact hgp sigma hsigma {z} (by simp [singletonChain]) z rfl
  · rintro ⟨hc, hgp⟩
    refine ⟨hc, (isMChain_singletonChain 0 {z}).2 (by simp [IsMSimplex]), ?_⟩
    intro sigma hsigma zeta hzeta q hq
    have hzetaEq : zeta = {z} := by
      simpa [singletonChain] using hzeta
    have hqz : q = z :=
      (Finset.singleton_inj.mp (hzetaEq.symm.trans hq)).symm
    subst q
    exact hgp sigma hsigma

omit [FiniteDimensional ℝ E] in
/-- For a basis one-chain, the chain-level general-position predicate is
exactly the direct one-simplex predicate (together with homogeneity of the
left chain). -/
theorem oneChainsInGeneralPosition_singleton_iff
    (n : ℕ) (c : Chain E) (omega : Finset E) :
    OneChainsInGeneralPosition n c (singletonChain omega) ↔
      IsMChain n c ∧ OneSimplexInGeneralPositionWithChain c omega := by
  constructor
  · rintro ⟨hc, homega, hgp⟩
    refine ⟨hc, (isMChain_singletonChain 1 omega).1 homega, ?_⟩
    intro sigma hsigma
    exact hgp sigma hsigma omega (by simp [singletonChain])
  · rintro ⟨hc, homega, hgp⟩
    refine ⟨hc, (isMChain_singletonChain 1 omega).2 homega, ?_⟩
    intro sigma hsigma tau htau
    have htauEq : tau = omega := by
      simpa [singletonChain] using htau
    subst tau
    exact hgp sigma hsigma

omit [FiniteDimensional ℝ E] in
/-- From a point in chainwise general position, choose a distinct endpoint
outside the chain so that the connecting one-simplex is also in chainwise
general position. -/
theorem exists_generalPosition_endpoint
    (n : ℕ) (c : Chain E) (z : E)
    (hdim : Module.finrank ℝ E = n) (hn : 0 < n)
    (hc : IsMChain n c)
    (hz : PointInGeneralPositionWithChain c z) :
    ∃ u : E, u ∉ chainRealization c ∧
      OneSimplexInGeneralPositionWithChain c ({z, u} : Finset E) := by
  obtain ⟨u, huSupport, huObstacle⟩ :=
    exists_endpoint_outside_chain_and_obstacles n c z hdim hn hc
  have hzObstacle : z ∈ segmentObstacleLocus c z := by
    rw [segmentObstacleLocus]
    apply Set.mem_iUnion.mpr
    refine ⟨({z} : Finset E), Set.mem_iUnion.mpr ⟨?_, ?_⟩⟩
    · simp [segmentObstacleSets]
    · exact mem_affineSpan ℝ (by simp)
  have hzu : z ≠ u := by
    intro h
    apply huObstacle
    simpa [h] using hzObstacle
  have huSigma (sigma : Finset E) (hsigma : sigma ∈ c.support) :
      u ∉ realization sigma := by
    intro hu
    apply huSupport
    rw [chainRealization]
    apply Set.mem_iUnion.mpr
    exact ⟨sigma, Set.mem_iUnion.mpr ⟨hsigma, hu⟩⟩
  refine ⟨u, huSupport, ?_⟩
  refine ⟨by simp [IsMSimplex, hzu], ?_⟩
  intro sigma hsigma
  refine ⟨by simp [IsMSimplex, hzu], ?_, ?_⟩
  · intro q hq
    simp only [Finset.mem_insert, Finset.mem_singleton] at hq
    rcases hq with rfl | rfl
    · exact hz sigma hsigma
    · intro v hv huFacet
      exact huSigma sigma hsigma (realization_erase_subset sigma v huFacet)
  · intro v hv
    refine ⟨by simp [IsMSimplex, hzu], ?_, ?_⟩
    · intro q hq
      simp only [Finset.mem_insert, Finset.mem_singleton] at hq
      rcases hq with rfl | rfl
      · exact hz sigma hsigma v hv
      · intro huFacet
        exact huSigma sigma hsigma
          (realization_erase_subset sigma v huFacet)
    · intro w hw
      apply disjoint_segment_realization_of_not_mem_affineSpan_insert
      · intro hzFace
        exact hz sigma hsigma v hv
          (realization_mono (Finset.erase_subset w (sigma.erase v)) hzFace)
      · intro huSpan
        apply huObstacle
        rw [segmentObstacleLocus]
        apply Set.mem_iUnion.mpr
        refine ⟨insert z ((sigma.erase v).erase w),
          Set.mem_iUnion.mpr ⟨?_, by simpa using huSpan⟩⟩
        rw [segmentObstacleSets]
        simp only [Finset.mem_insert]
        right
        apply Finset.mem_biUnion.mpr
        refine ⟨sigma, hsigma, ?_⟩
        apply Finset.mem_biUnion.mpr
        refine ⟨v, hv, ?_⟩
        exact Finset.mem_image.mpr ⟨w, hw, rfl⟩

omit [FiniteDimensional ℝ E] in
/-- Point intersection of a chain with a singleton zero-chain, expanded over
the simplices in the chain. -/
theorem pointChainIntersection_singleton_right
    (c : Chain E) (z : E) :
    pointChainIntersection c (singletonChain {z}) =
      c.sum fun sigma a ↦ a * pointIntersectionNumber sigma z := by
  rw [pointChainIntersection, chainPairing]
  apply Finsupp.sum_congr
  intro sigma a
  simp [singletonChain]

omit [FiniteDimensional ℝ E] in
/-- Additivity of point intersection in the zero-chain argument. -/
theorem pointChainIntersection_add_right
    (c d d' : Chain E) :
    pointChainIntersection c (d + d') =
      pointChainIntersection c d + pointChainIntersection c d' := by
  exact chainPairing_add_right pointSimplexIntersectionNumber c d d'

omit [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E] in
/-- The boundary of a literal one-simplex consists of its two endpoints. -/
theorem boundary_pair (z u : E) (hzu : z ≠ u) :
    boundary (singletonChain ({z, u} : Finset E)) =
      singletonChain {z} + singletonChain {u} := by
  rw [boundary_singletonChain, boundarySimplex]
  have heraseZ : ({z, u} : Finset E).erase z = {u} := by
    ext p
    simp [hzu]
  have heraseU : ({z, u} : Finset E).erase u = {z} := by
    ext p
    simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton]
    aesop
  simp [hzu, heraseZ, heraseU, add_comm]

omit [FiniteDimensional ℝ E] in
/-- Point intersection with the boundary of a literal one-simplex expands
as the sum of the two endpoint intersections. -/
theorem pointChainIntersection_boundary_pair
    (c : Chain E) (z u : E) (hzu : z ≠ u) :
    pointChainIntersection c
        (boundary (singletonChain ({z, u} : Finset E))) =
      pointChainIntersection c (singletonChain {z}) +
        pointChainIntersection c (singletonChain {u}) := by
  rw [boundary_pair z u hzu]
  exact pointChainIntersection_add_right c _ _

omit [FiniteDimensional ℝ E] in
/-- A point outside the realization of every supported simplex has zero
intersection number with the chain. -/
theorem pointChainIntersection_singleton_eq_zero_of_forall_not_mem
    (c : Chain E) (z : E)
    (h : ∀ sigma ∈ c.support, z ∉ realization sigma) :
    pointChainIntersection c (singletonChain {z}) = 0 := by
  rw [pointChainIntersection_singleton_right]
  rw [Finsupp.sum]
  apply Finset.sum_eq_zero
  intro sigma hsigma
  simp [pointIntersectionNumber, h sigma hsigma]

/-- The positive-dimension hypothesis in Lemma 10.2 is mathematically
necessary.  In the zero vector space there is a nonzero zero-chain, every
universal premise over one-simplices is vacuous, and its point-intersection
number at the unique point is one. -/
theorem lemma10_2_requires_positive_dimension :
    ∃ (c : Chain (Fin 0 → ℝ)) (z : Fin 0 → ℝ),
      IsMChain 0 c ∧ PointInGeneralPositionWithChain c z ∧
        (∀ omega : Finset (Fin 0 → ℝ),
          OneSimplexInGeneralPositionWithChain c omega →
            pointChainIntersection c
              (boundary (singletonChain omega)) = 0) ∧
        pointChainIntersection c (singletonChain {z}) ≠ 0 := by
  let z : Fin 0 → ℝ := 0
  refine ⟨singletonChain {z}, z, ?_, ?_, ?_, ?_⟩
  · exact (isMChain_singletonChain 0 {z}).2 (by simp [IsMSimplex])
  · intro sigma hsigma
    have hsigmaEq : sigma = {z} := by
      simpa [singletonChain] using hsigma
    subst sigma
    intro v hv
    have hvz : v = z := by simpa using hv
    subst v
    simp [realization]
  · intro omega homega
    have hcard : omega.card = 2 := by
      simpa [IsMSimplex] using homega.1
    have hle : omega.card ≤ 1 :=
      Finset.card_le_one.mpr fun _ _ _ _ ↦ Subsingleton.elim _ _
    omega
  · simp [z, pointIntersectionNumber, realization]

omit [FiniteDimensional ℝ E] in
/-- Lemma 10.2.  The hypothesis `0 < n` is necessary: in dimension zero
there are no one-simplices, so the universal premise would otherwise be
vacuous. -/
theorem lemma10_2
    (n : ℕ) (c : Chain E)
    (hdim : Module.finrank ℝ E = n) (hn : 0 < n)
    (hc : IsMChain n c)
    (hboundary : ∀ omega : Finset E,
      OneSimplexInGeneralPositionWithChain c omega →
        pointChainIntersection c (boundary (singletonChain omega)) = 0)
    (z : E) (hz : PointInGeneralPositionWithChain c z) :
    pointChainIntersection c (singletonChain {z}) = 0 := by
  obtain ⟨u, huOutside, hzuGeneral⟩ :=
    exists_generalPosition_endpoint n c z hdim hn hc hz
  have hzu : z ≠ u := by
    intro h
    subst u
    simpa [OneSimplexInGeneralPositionWithChain, IsMSimplex] using
      hzuGeneral.1
  have huZero : pointChainIntersection c (singletonChain {u}) = 0 := by
    apply pointChainIntersection_singleton_eq_zero_of_forall_not_mem
    intro sigma hsigma huSigma
    apply huOutside
    rw [chainRealization]
    apply Set.mem_iUnion.mpr
    exact ⟨sigma, Set.mem_iUnion.mpr ⟨hsigma, huSigma⟩⟩
  have hpairZero := hboundary ({z, u} : Finset E) hzuGeneral
  rw [pointChainIntersection_boundary_pair c z u hzu, huZero, add_zero] at hpairZero
  exact hpairZero

end EuclideanIntersection
end BeyondSperner
